/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_androidex_MainActivity2_EVSystem_Elevator */

#ifndef _Included_com_example_androidex_MainActivity2_EVSystem_Elevator
#define _Included_com_example_androidex_MainActivity2_EVSystem_Elevator
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
