/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_androidex_MainActivity2_EVSystem */

#ifndef _Included_com_example_androidex_MainActivity2_EVSystem
#define _Included_com_example_androidex_MainActivity2_EVSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_androidex_MainActivity2_EVSystem
 * Method:    getSwitch
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_androidex_MainActivity2_00024EVSystem_getSwitch
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_androidex_MainActivity2_EVSystem
 * Method:    getIntrBtn
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_androidex_MainActivity2_00024EVSystem_getIntrBtn
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_androidex_MainActivity2_EVSystem
 * Method:    setDot
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_androidex_MainActivity2_00024EVSystem_setDot
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_androidex_MainActivity2_EVSystem
 * Method:    setLed
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_androidex_MainActivity2_00024EVSystem_setLed
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_androidex_MainActivity2_EVSystem
 * Method:    setBuzzer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_androidex_MainActivity2_00024EVSystem_setBuzzer
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_androidex_MainActivity2_EVSystem
 * Method:    callSyscall
 * Signature: (II[I[I)I
 */
JNIEXPORT jint JNICALL Java_com_example_androidex_MainActivity2_00024EVSystem_callSyscall
  (JNIEnv *, jobject, jint, jint, jintArray, jintArray);

/*
 * Class:     com_example_androidex_MainActivity2_EVSystem
 * Method:    openDevicea
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_androidex_MainActivity2_00024EVSystem_openDevicea
  (JNIEnv *, jobject);

/*
 * Class:     com_example_androidex_MainActivity2_EVSystem
 * Method:    openDeviceb
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_androidex_MainActivity2_00024EVSystem_openDeviceb
  (JNIEnv *, jobject);

/*
 * Class:     com_example_androidex_MainActivity2_EVSystem
 * Method:    closeDevice
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_androidex_MainActivity2_00024EVSystem_closeDevice
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
