/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_androidex_MainActivity2_StateMove */

#ifndef _Included_com_example_androidex_MainActivity2_StateMove
#define _Included_com_example_androidex_MainActivity2_StateMove
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
