/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_ndk_EVSystem_Elevator */

#ifndef _Included_org_example_ndk_EVSystem_Elevator
#define _Included_org_example_ndk_EVSystem_Elevator
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
