/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_ndk_EVSystem */

#ifndef _Included_org_example_ndk_EVSystem
#define _Included_org_example_ndk_EVSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_ndk_EVSystem
 * Method:    getSwitch
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_example_ndk_EVSystem_getSwitch
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_example_ndk_EVSystem
 * Method:    getIntrBtn
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_example_ndk_EVSystem_getIntrBtn
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_example_ndk_EVSystem
 * Method:    setDot
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_example_ndk_EVSystem_setDot
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_example_ndk_EVSystem
 * Method:    setLed
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_example_ndk_EVSystem_setLed
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_example_ndk_EVSystem
 * Method:    setBuzzer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_example_ndk_EVSystem_setBuzzer
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_example_ndk_EVSystem
 * Method:    callSyscall
 * Signature: (II[I[I)I
 */
JNIEXPORT jint JNICALL Java_org_example_ndk_EVSystem_callSyscall
  (JNIEnv *, jobject, jint, jint, jintArray, jintArray);

/*
 * Class:     org_example_ndk_EVSystem
 * Method:    openDevicea
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_example_ndk_EVSystem_openDevicea
  (JNIEnv *, jobject);

/*
 * Class:     org_example_ndk_EVSystem
 * Method:    openDeviceb
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_example_ndk_EVSystem_openDeviceb
  (JNIEnv *, jobject);

/*
 * Class:     org_example_ndk_EVSystem
 * Method:    closeDevice
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_example_ndk_EVSystem_closeDevice
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
