/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EVSystem */

#ifndef _Included_EVSystem
#define _Included_EVSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     EVSystem
 * Method:    getSwitch
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_EVSystem_getSwitch
  (JNIEnv *, jobject);

/*
 * Class:     EVSystem
 * Method:    getIntrBtn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_EVSystem_getIntrBtn
  (JNIEnv *, jobject);

/*
 * Class:     EVSystem
 * Method:    setDot
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_EVSystem_setDot
  (JNIEnv *, jobject, jint);

/*
 * Class:     EVSystem
 * Method:    setLed
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_EVSystem_setLed
  (JNIEnv *, jobject, jint);

/*
 * Class:     EVSystem
 * Method:    setBuzzer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_EVSystem_setBuzzer
  (JNIEnv *, jobject);

/*
 * Class:     EVSystem
 * Method:    callSyscall
 * Signature: (II[I[I)I
 */
JNIEXPORT jint JNICALL Java_EVSystem_callSyscall
  (JNIEnv *, jobject, jint, jint, jintArray, jintArray);

/*
 * Class:     EVSystem
 * Method:    openDevice
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_EVSystem_openDevice
  (JNIEnv *, jobject);

/*
 * Class:     EVSystem
 * Method:    closeDevice
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_EVSystem_closeDevice
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
