/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EVSystem_Elevator */

#ifndef _Included_EVSystem_Elevator
#define _Included_EVSystem_Elevator
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
