/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EVSystem_Floor_Person */

#ifndef _Included_EVSystem_Floor_Person
#define _Included_EVSystem_Floor_Person
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
