/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EVSystem_Floor */

#ifndef _Included_EVSystem_Floor
#define _Included_EVSystem_Floor
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
